### ISSUE TITLE
[plex-frontend7] Als projectleider, wil ik de voorkeuren van de studenten kunnen zien, zodat ik naderhand eenvoudig projectgroepen kan maken met deelnemers die dezelfde voorkeur hebben.

### ISSUE THREAD

**Issue by Leonvandervleuten** [projectleaderexcellenceplatform/plex-frontend#9]
- [x] Student view overzicht keuze
- [x] Front-end React (HTML, CSS) - Geen functionaliteiten met back-end
- [x] Overzicht van studenten. Groen = keuze opgegeven, rood = geen keuze opgegeven
- [x] Project keuze per student zichtbaar
- [x] List + Grid weergave
- [ ] Testen bij implementatie functies

**Comment by ksmits-design** [comment]
![Plex - Settings – 1](https://user-images.githubusercontent.com/102230295/165295746-9c59cb34-d835-43b4-a433-275eba8c9f10.png)
![Plex - Project confirm - Student view – 3](https://user-images.githubusercontent.com/102230295/165295755-7ff1d477-c327-47a4-a474-acdb9c66be07.png)
![Plex - Project confirm - student list list view](https://user-images.githubusercontent.com/102230295/165295764-bcc2e6ef-4e11-4cff-8a14-9221f4662bce.png)
![Plex - Project confirm - student list - board view (2)](https://user-images.githubusercontent.com/102230295/165295771-335ae865-5568-4250-b4d2-c49e61ee56d3.png)
![Plex - Project confirm - Project Details](https://user-images.githubusercontent.com/102230295/165295778-571a8420-bdbe-4cd5-961e-2f2e2ed25d7b.png)

**Comment by amirfahimnia** [comment]
Top Leon!
